version: "3"

services:
  zk:
    image: mesoscloud/zookeeper:3.4.6-centos-7
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"
    expose:
      - "2181"
      - "2888"
      - "3888"
    network_mode: host
    environment:
      ZK_CONFIG: tickTime=2000,initLimit=10,syncLimit=5,maxClientCnxns=128,forceSync=no,clientPort=2181
      ZK_ID: 1

  master:
    image: mesosphere/mesos-master:1.0.1-2.0.93.ubuntu1404
    network_mode: host
    ports:
      - "5050:5050"
    environment:
      MESOS_ZK: zk://127.0.0.1:2181/mesos
      MESOS_QUORUM: 1
      MESOS_CLUSTER: docker-compose
      MESOS_REGISTRY: replicated_log # default is in_memory for some reason
      MESOS_HOSTNAME: 127.0.0.1
      LIBPROCESS_IP: 127.0.0.1
    depends_on:
      - zk

  slave-one:
    image: mesosphere/mesos-slave:1.0.1-2.0.93.ubuntu1404
    network_mode: host
    pid: host
    environment:
      MESOS_MASTER: zk://127.0.0.1:2181/mesos
      MESOS_CONTAINERIZERS: docker,mesos
      MESOS_PORT: 5051
      MESOS_RESOURCES: ports(*):[11000-11999]
      MESOS_HOSTNAME: 127.0.0.1
      LIBPROCESS_IP: 127.0.0.1
      MESOS_WORK_DIR: /tmp/mesos
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
      # - /usr/local/bin/docker:/usr/bin/docker
      - /usr/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zk

  # slave-two:
  #   image: mesosphere/mesos-slave:1.0.1-2.0.93.ubuntu1404
  #   network_mode: host
  #   pid: host
  #   environment:
  #     MESOS_MASTER: zk://127.0.0.1:2181/mesos
  #     MESOS_CONTAINERIZERS: docker,mesos
  #     MESOS_PORT: 5052
  #     MESOS_RESOURCES: ports(*):[12000-12999]
  #     MESOS_HOSTNAME: 127.0.0.1
  #     LIBPROCESS_IP: 127.0.0.1
  #   volumes:
  #     - /sys/fs/cgroup:/sys/fs/cgroup
  #     - /usr/local/bin/docker:/usr/bin/docker
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   depends_on:
  #     - zk

  marathon:
    image: mesosphere/marathon:v1.3.0
    ports:
      - "8080:8080"
    network_mode: host
    environment:
      MARATHON_MASTER: zk://127.0.0.1:2181/mesos
    depends_on:
      - zk

  chronos:
    image: mesosphere/chronos:v3.0.2
    ports:
      - "4400:4400"
      - "4401:4401"
    # command: /usr/bin/chronos run_jar --http_port 8888 --master zk://127.0.0.1:2181/mesos --zk_hosts zk://127.0.0.1:2181/mesos
    command: " --zk_hosts 127.0.0.1:2181 --master zk://127.0.0.1:2181/mesos"
    network_mode: host
    environment:
      PORT0: 4400
      PORT1: 4401
    depends_on:
      - zk



  # metronome:
  #   image: mesoshq/metronome:0.2.0
  #   network_mode: host
  #   environment:
  #     metronome_mesos_master_url: 127.0.0.1:5050
  #     metronome_zk_url: zk://127.0.0.1:2181/mesos
  #     PORT0: 8081
  #     LIBPROCESS_IP: 127.0.0.1
  #   depends_on:
  #     - zk
  #     - master
